### ISSUE TITLE
You cant import classes

### ISSUE THREAD

**Issue by davidot** [Sinius15/JavaJavaParser#1]
You cant import classes so 
import java.awt.test;
import java.cookie.asfd;
import some.java.clas;
should be either
import java.awt.test._;
import java.cookie.asfd._;
import some.java.clas.*;
or 
import java.awt.Test;
import java.cookie.Asfd;
import some.java.Clas;
unless the classes start with non capital letters.

**Comment by Sinius15** [comment]
Of course. Thanks for notecing. I will change it in the next version.

**Comment by Sinius15** [comment]
Fixed! 64d1f56f33885c350073d81c3cff0c995097f6d6
